const messages = {
    BELOW_SPONSOR_MINIMUM: 'The amount is too small for Gas Assist.',
    ABOVE_SPONSOR_MAXIMUM: 'The amount is above the Gas Assist limit.',
    GAS_ASSIST_RULE_NOT_FOUND: 'Gas Assist is not available for this token yet.',
    SWAP_INTENT_NOT_CUSTOM_CONTRACT: 'This route cannot use Gas Assist.',
    ONCHAIN_APPROVAL_REQUIRED: 'This token needs an approval before it can be swapped.',
    UNLIMITED_PERMIT_NOT_ALLOWED: 'This token requested an unsafe unlimited approval.',
    SELL_VALUE_TOO_LOW: 'The swap amount is too small for Gas Assist.',
    GAS_ASSIST_FEE_NOT_REPRESENTABLE: 'The Gas Assist fee is too large for this trade.',
    GROSS_TRADE_VALUE_UNECONOMIC: 'The swap amount is too small for Gas Assist.',
    NET_TRADE_VALUE_UNECONOMIC: 'Too little would remain to swap after the Gas Assist fee.',
    PAYMENT_EXCEEDS_GROSS_INPUT: 'The Gas Assist fee would leave nothing to swap.',
    OUTPUT_VALUE_UNECONOMIC: 'The expected output is too small.',
    PAYMENT_TRANSFER_UNECONOMIC: 'This amount is too small to cover the sponsored transaction.',
    USER_OUTPUT_TOO_LOW: 'The expected output is too small after fees.',
    PRICE_IMPACT_TOO_HIGH: 'Price impact is too high for this swap.',
    QUOTE_EXPIRED: 'The price expired. Refresh and try again.',
    INTENT_EXPIRED: 'This wallet request expired. Try again.',
    ORDER_EXPIRED: 'This Gas Assist quote expired. Create a fresh quote.',
    ACTIVE_ORDER_EXISTS: 'A Gas Assist swap is already active for this wallet.',
    ORDER_REQUOTE_REQUIRED: 'The price changed too much. Refresh and try again.',
    SPONSORED_ROUTE_UNAVAILABLE: 'No safe Gas Assist route is available right now.',
    PRESIGNED_PACKAGE_REQUIRES_UNISWAP: 'This route cannot currently use the one-tap Gas Assist flow.',
    PRESIGNED_PACKAGE_NONCE_MISMATCH: 'Your wallet nonce changed. Refresh and try again.',
    SPONSORSHIP_PACKAGE_NONCE_MISMATCH: 'Your wallet nonce changed. Refresh and try again.',
    PRESIGNED_PACKAGE_STATE_CONFLICT: 'This Gas Assist swap changed state. Refresh its status.',
    ORDER_STATE_CONFLICT: 'This Gas Assist swap changed state. Refresh its status.',
    PAYMENT_TOKEN_DISABLED: 'Gas Assist is no longer available for this token.',
    PAYMENT_TOKEN_EVIDENCE_STALE: 'This token cannot be safely priced right now.',
    INSUFFICIENT_PAYMENT_TOKEN_BALANCE: 'Your token balance is too low for this swap.',
    PAYMASTER_REJECTED: 'The sponsor declined this transaction.',
    PAYMASTER_TIMEOUT: 'The sponsor service timed out. Try again.',
    PAYMASTER_UNAVAILABLE: 'The sponsor service is temporarily unavailable.',
    PAYMASTER_POLICY_TIMEOUT: 'The sponsor policy service timed out. Try again.',
    PAYMASTER_POLICY_UNAVAILABLE: 'The sponsor policy service is temporarily unavailable.',
    PAYMASTER_POLICY_UPDATE_FAILED: 'The sponsor could not authorize this exact transaction.',
    SPONSORSHIP_NETWORK_ERROR: 'Could not reach Gas Assist. Check your connection and try again.',
    SPONSORSHIP_REQUEST_ABORTED: 'The Gas Assist request was cancelled.',
    SPONSORSHIP_INVALID_RESPONSE: 'Gas Assist returned an invalid response.',
    SPONSORSHIP_EMPTY_RESPONSE: 'Gas Assist returned an empty response.',
    SPONSORSHIP_CONFIG_LOADING: 'Gas Assist is still loading.',
    SPONSORSHIP_CONFIG_UNAVAILABLE: 'Gas Assist configuration could not be loaded.',
    SPONSORSHIP_DISABLED: 'Gas Assist is currently unavailable.',
    SPONSORSHIP_CONTEXT_MISSING: 'This Gas Assist session ended. Start again.',
    PISTACHIO_ACCOUNT_MISMATCH: 'The connected wallet changed. Start again.',
    PISTACHIO_WALLET_REQUIRED: 'Gas Assist requires Pistachio Wallet.',
    WALLET_NOT_CONNECTED: 'Connect Pistachio Wallet first.',
    SWAP_TOKENS_MISSING: 'Choose both swap tokens first.',
    SWAP_AMOUNT_INVALID: 'Enter a valid token amount.',
    SLIPPAGE_INVALID: 'The slippage setting is invalid.',
}

/** Presents a concise user-safe Gas Assist error while diagnostics remain in the technical drawer and console. */
export default function GasAssistError({ error }) {
    const code = typeof error === 'string' ? error : error?.code
    const message = messages[code] ?? error?.message ?? 'This trade cannot use Gas Assist right now.'
    return <p className="gas-assist-error" role="alert">{message}</p>
}
